apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bassco/argocd-lab.git
        revision: HEAD
        directories:
          - path: infra/*
  template:
    metadata:
      name: "{{ path.basename }}"
    spec:
      project: infrastructure
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/bassco/argocd-lab.git
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: in-cluster
        namespace: "{{ path.basename }}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
