apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/bassco/argocd-lab.git"
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "argocd-tooling"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
