---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/bassco/argocd-lab.git"
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "argocd-tooling"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  syncWindows:
    - kind: allow
      schedule: "*/10 8-23 * * 1-5"
      timeZone: "Europe/Berlin"
      duration: 5m
      manualSync: true
      clusters:
        - in-cluster
      namespaces:
        - argocd
        - argocd-tooling
